openapi: 3.0.3
info:
  title: API de Ordens de Compra
  description: API para cadastro, consulta e listagem de ordens de compra.
  version: "1.0.0"
servers:
  - url: http://localhost:9092
tags:
  - name: orders
    description: Operações relacionadas a ordens de compra

paths:
  /orders:
    get:
      tags:
        - orders
      summary: Listar todas as ordens de compra
      description: Retorna uma lista de todas as ordens de compra.
      responses:
        '200':
          description: Lista de ordens de compra
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ordersResponse'
    post:
      tags:
        - orders
      summary: Criar uma nova ordem de compra
      description: Adiciona uma nova ordem de compra ao sistema.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '201':
          description: Ordem criada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/orderResponse'
        '400':
          description: Erro na requisição
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'

  /orders/{id}:
    get:
      tags:
        - orders
      summary: Buscar ordem de compra por ID
      description: Retorna os detalhes de uma ordem de compra específica.
      parameters:
        - name: id
          in: path
          required: true
          description: ID da ordem de compra
          schema:
            type: integer
      responses:
        '200':
          description: Ordem encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/orderResponse'
        '404':
          description: Ordem não encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'

components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: integer
          description: ID da ordem de compra
          example: 1
        product_id:
          type: integer
          description: ID do produto
          example: 2
        quantity:
          type: integer
          description: Quantidade do produto
          example: 5
    ordersResponse:
      type: array
      items:
        $ref: '#/components/schemas/Order'
    orderResponse:
      type: object
      properties:
        id:
          type: integer
        product_id:
          type: integer
        quantity:
          type: integer
    errorResponse:
      type: object
      properties:
        message:
          type: string
          example: Erro ao processar requisição