name: CI - Produção

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  prod-pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Rodar testes do product_api
        run: |
          cd 85ESE/product_api
          go test ./...

      - name: Rodar testes do images
        run: |
          cd 85ESE/images
          go test ./...
