name: CI - Produção

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verificar-origem:
    runs-on: ubuntu-latest
    steps:
      - name: Verificando branch de origem
        if: github.event_name == 'pull_request'
        run: |
          echo "PR vindo de: ${{ github.head_ref }}"
          if [[ "${{ github.head_ref }}" != "dev" ]]; then
            echo "❌ Pull Request para 'main' só é permitido se vier da branch 'dev'."
            exit 1
          else
            echo "✅ Origem válida."
          fi

  prod-pipeline:
    needs: verificar-origem
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Rodar testes do product_api
        run: |
          cd 85ESE/product_api
          go test ./...

      - name: Rodar testes do images
        run: |
          cd 85ESE/images
          go test ./...
