name: CI - Desenvolvimento

on:
  push:
    branches:
      - dev

jobs:
  dev-pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Rodar testes na dev
        run: |
          cd 85ESE/product_api
          go test ./...
